require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - bin/{rails,rake}
    - db/migrate/*
    - db/schema.rb
    - node_modules/**/*
    - script/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
