inherit_mode:
  merge:
    - CountAsOne
    - Environments
    - Exclude

require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - bin/{rails,rake}
    - db/migrate/*
    - db/schema.rb
    - "**/node_modules/**/*"
    - script/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Style/Documentation:
  Enabled: false
